#!/bin/bash +h

#version 0.20.1

extract $0 &&
if [ $1 -eq 1 ]; then
    ./configure --disable-shared &&
    make -j $procs &&
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /tools/bin
elif [ $1 -eq 2 ]; then
    sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
    sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in &&
    sed -e '/AppData/{N;N;p;s/\.appdata\./.metainfo./}' -i gettext-tools/its/appdata.loc &&
    ./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/gettext-0.19.8.1 &&
    make -j $procs &&
    make -j $procs install &&
    chmod -v 0755 /usr/lib/preloadable_libintl.so
fi &&
remove $0
