#!/bin/bash +h

#version 1.10

extract $0 &&
if [ $1 -eq 1 ]; then ./configure --prefix=/tools
elif [ $1 -eq 2 ]; then ./configure --prefix=/usr
fi &&
make -j $procs &&
make -j $procs install &&
if [ $1 -eq 2 ]; then mv -vf /usr/bin/gzip /bin; fi &&
remove $0
